export const testimonialsDataTwo = [
    {
      id: 1,
      name: "Padma Shri Resul Pookutty",
      review: "Indian Sound Designer",
      offset: 100,
      image: "img/IICS/iics_image/industry-mentors/Padma-Shri-Resul-Pookutty.png",
    },
    {
      id: 2,
      name: "Padma Shri Shankar Mahadevan",
      review: "Indian singer and composer",
      offset: 200,
      image: "img/IICS/iics_image/industry-mentors/Padma-Shri-Shankar-Mahadevan.png",
    },
    {
      id: 3,
      name: "Ms.Dia Mirza",
      review: "Actor",
      offset: 300,
      image: "img/IICS/iics_image/industry-mentors/Ms-Dia-Mirza.jpg",
    },
    {
      id: 4,
      name: "Ms. Kavita Krishnamurthy",
      review: "Indian playback singer",
      offset: 400,
      image: "img/IICS/iics_image/industry-mentors/Ms-Kavita-Krishnamurthy.png",
    },
    {
      id: 5,
      name: "Ms. Neeta Lulla",
      review: "Costume Designer",
      offset: 500,
      image: "img/IICS/iics_image/industry-mentors/Ms-Neeta-Lulla.png",
    },
    {
      id: 6,
      name: "Ms. Revathy Asha Kelunni",
      review: "Actor/ Filmmaker",
      offset: 600,
      image: "img/IICS/iics_image/industry-mentors/Ms-Revathy-Asha-Kelunni.png",
    },
    {
      id: 7,
      name: "Mr. Zakir Khan",
      review: "Comedian",
      offset: 700,
      image: "img/IICS/iics_image/industry-mentors/zakir-khan.png",
    },
    {
      id: 8,
      name: "Ms.Sushma Gaikwad",
      review: "Co-founder Ice Global, Wizcraft MIME & Sukhoon",
      offset: 800,
      image: "img/IICS/iics_image/industry-mentors/sushma.png",
    },
    {
      id: 9,
      name: "Mr. Suresh Eriyat",
      review: "Production Designer",
      offset: 900,
      image: "img/IICS/iics_image/industry-mentors/Mr-Suresh-Eriyat.png",
    },
    {
      id: 10,
      name: "Mr. Bharat Dabholkar",
      review: "Actor",
      offset: 1000,
      image: "img/IICS/iics_image/industry-mentors/Mr-Bharat-Dabholkar.png",
    },
    {
      id: 11,
      name: "Mr. Amit Sadh",
      review: "Actor",
      offset: 1100,
      image: "img/IICS/iics_image/industry-mentors/amit-sadh.png",
    },
    {
      id: 12,
      name: "Mr. Sameer Tobaccowala",
      review: "CEO, Shobiz Experiential Communications",
      offset: 1200,
      image: "img/IICS/iics_image/industry-mentors/sameer-tobaccowala.png",
    },
    {
      id: 13,
      name: "Mr. Amit Behl",
      review: "Indian Theater Actor",
      offset: 1300,
      image: "img/IICS/iics_image/industry-mentors/amit-behl.png",
    },
    {
      id: 14,
      name: "Ms. Bina Paul",
      review: "Indian film editor",
      offset: 1400,
      image: "img/IICS/iics_image/industry-mentors/bina-paul.png",
    },
    {
      id: 15,
      name: "Mr. Omung Kumar",
      review: "Sound Designer",
      offset: 1500,
      image: "img/IICS/iics_image/industry-mentors/omung_kumar.png",
    },
    {
      id: 16,
      name: "Mr. Kamlesh Pandey",
      review: "Writer",
      offset: 1600,
      image: "img/IICS/iics_image/industry-mentors/Mr-Kamlesh-Pandey_.png",
    },
    {
      id: 17,
      name: "Mr. Shayam Kaushal",
      review: "Director",
      offset: 1700,
      image: "img/IICS/iics_image/industry-mentors/Mr-Shayam-Kaushal.png",
    },
    {
      id: 18,
      name: "Ms. Jaya Bhattacharya",
      review: "Indian television actress",
      offset: 1800,
      image: "img/IICS/iics_image/industry-mentors/jaya-bhattacharya.png",
    },
    {
      id: 19,
      name: "Mr. Rahul Rawail",
      review: "Indian Film Director",
      offset: 1900,
      image: "img/IICS/iics_image/industry-mentors/Mr-Rahul-Rawail.png",
    },
    {
      id: 20,
      name: "Mr. Jaya Kumar",
      review: "Toonz Media Group Holdings Pvt Ltd",
      offset: 2000,
      image: "img/IICS/iics_image/industry-mentors/jaya-kumar.png",
    },
    {
      id: 21,
      name: "Mr. Jan Horn",
      review: "Managing Director of SAE Dubai University",
      offset: 2100,
      image: "img/IICS/iics_image/industry-mentors/Mr-jan-horn.png",
    },
    {
      id: 22,
      name: "Mr. Salim Arif",
      review: "Indian Theatre & Film Actor",
      offset: 2200,
      image: "img/IICS/iics_image/industry-mentors/salim-arif.png",
    },
    {
      id: 23,
      name: "Dr. L. Subramaniam",
      review: "Indian Violinist",
      offset: 2300,
      image: "img/IICS/iics_image/industry-mentors/L-Subramaniam-4.png",
    },
    {
      id: 24,
      name: "Mr. Kausar Munir",
      review: "Lyricist/Writer",
      offset: 2400,
      image: "img/IICS/iics_image/industry-mentors/mr-kausar-munir.png",
    },
    {
      id: 25,
      name: "Mr. Anupam Shobhakar",
      review: "Indian musician, composer, instrumentalist, record producer, and classically trained sarodist",
      offset: 2500,
      image: "img/IICS/iics_image/industry-mentors/Mr-Anupam-Shobhakar.png",
    },
    {
      id: 26,
      name: "Mr. Vaibhav Kumaresh",
      review: "Founder, Director",
      offset: 2600,
      image: "img/IICS/iics_image/industry-mentors/vaibhav-kumaresh.png",
    },
    {
      id: 27,
      name: "Mr. Sumanto Ray",
      review: "Actor, Voice Artist, Dubbing Director, Dialogue writer, Music creator",
      offset: 2700,
      image: "img/IICS/iics_image/industry-mentors/Sumanto-Ray-.png",
    },
    {
      id: 28,
      name: "Ms.Anusha Srinivasan Iyer",
      review: "Digital Creator, Filmaker, Director",
      offset: 2800,
      image: "img/IICS/iics_image/industry-mentors/anusha-mam_.png",
    },
    {
      id: 29,
      name: "Mr. Sudeep Chatterjee",
      review: "Cinematographer",
      offset: 2900,
      image: "img/IICS/iics_image/industry-mentors/sudeep-Chatterjee.png",
    },
    {
      id: 30,
      name: "Mr. Avijit Dutt",
      review: "Advertisement Agency",
      offset: 3000,
      image: "img/IICS/iics_image/industry-mentors/Avijit-dutt.png",
    },
    {
      id: 31,
      name: "Mr. Vishnu Patel",
      review: "Group CEO – Special Projects",
      offset: 3100,
      image: "img/IICS/iics_image/industry-mentors/Vishnu-Patel.png",
    },
    {
      id: 32,
      name: "Ms. Kireet khurana",
      review: "Climb Media (I) Pvt. Ltd",
      offset: 3200,
      image: "img/IICS/iics_image/industry-mentors/Ms-Kireet-khurana.png",
    },
    {
      id: 33,
      name: "Mr.Shibasish Sarkar",
      review: "Group CEO - Reliance Studios; Chairman/ Film Producer",
      offset: 3300,
      image: "img/IICS/iics_image/industry-mentors/Shibashish-Sarkar.png",
    },
    {
      id: 34,
      name: "Mr. Anand Jha",
      review: "Nilee Games",
      offset: 3400,
      image: "img/IICS/iics_image/industry-mentors/Mr-Anand-Jha.png",
    },
  ];